import {Montserrat} from "next/font/google";
import "./globals.css";
import Header from "@/components/ReuseComponent/Header";
import Footer from "@/components/ReuseComponent/Footer";


const montserrat = Montserrat({subsets: ["latin"]});

export const metadata = {
    title: "PG Vietnam",
    description: "Generated by create next app",
};
export default function RootLayout({children}) {

    return (
        <html lang="en">
        <body className={montserrat.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>


    );
}
